### ISSUE TITLE
Handling MalformedInputException properly

### ISSUE THREAD

**Issue by ddewaele** [apsaltis/nifi-gettcp-bundle#6]
When unable to decode in incoming byte, the processor will throw an exception and will stop working. Will require a manual restart.

We should handle these errors properly.
```
2016-12-14 04:01:36,887 ERROR [pool-31-thread-1] org.apache.nifi.processors.gettcp.GetTCP 
java.nio.charset.MalformedInputException: Input length = 1
        at java.nio.charset.CoderResult.throwException(CoderResult.java:281) ~[na:1.8.0_40]
        at java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:816) ~[na:1.8.0_40]
        at org.apache.nifi.processors.gettcp.GetTCP$SocketRecveiverThread.run(GetTCP.java:613) ~[nifi-gettcp-processors-1.0.0.jar:1.0.0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_40]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_40]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_40]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_40]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40]
```

**Comment by apsaltis** [comment]
Good catch. This should certainly be handled correctly.
