### ISSUE TITLE
Processor stuck on socketChannel.read

### ISSUE THREAD

**Issue by ddewaele** [apsaltis/nifi-gettcp-bundle#7]
Under some conditions the code can hang on `socketChannel.read(buf)`

```
                while (keepProcessing) {
                    if (socketChannel.isOpen() && socketChannel.isConnected()) {
                        nBytes = socketChannel.read(buf);
                        if (-1 == nBytes) {
```

Resulting in the processor getting stuck and unable to process any messages.

```
2016-12-14 07:38:49,264 INFO [NiFi logging handler] org.apache.nifi.StdOut "pool-22-thread-1" #86 prio=5 os_prio=31 tid=0x00007fd885ec9000 nid=0xf503 runnable [0x0000000136503000]
2016-12-14 07:38:49,264 INFO [NiFi logging handler] org.apache.nifi.StdOut    java.lang.Thread.State: RUNNABLE
2016-12-14 07:38:49,264 INFO [NiFi logging handler] org.apache.nifi.StdOut      at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
2016-12-14 07:38:49,264 INFO [NiFi logging handler] org.apache.nifi.StdOut      at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
2016-12-14 07:38:49,264 INFO [NiFi logging handler] org.apache.nifi.StdOut      at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
2016-12-14 07:38:49,264 INFO [NiFi logging handler] org.apache.nifi.StdOut      at sun.nio.ch.IOUtil.read(IOUtil.java:197)
2016-12-14 07:38:49,264 INFO [NiFi logging handler] org.apache.nifi.StdOut      at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
2016-12-14 07:38:49,264 INFO [NiFi logging handler] org.apache.nifi.StdOut      - locked <0x00000007a2c130f0> (a java.lang.Object)
2016-12-14 07:38:49,264 INFO [NiFi logging handler] org.apache.nifi.StdOut      at org.apache.nifi.processors.gettcp.GetTCP$SocketRecveiverThread.run(GetTCP.java:587)
2016-12-14 07:38:49,264 INFO [NiFi logging handler] org.apache.nifi.StdOut      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2016-12-14 07:38:49,264 INFO [NiFi logging handler] org.apache.nifi.StdOut      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2016-12-14 07:38:49,264 INFO [NiFi logging handler] org.apache.nifi.StdOut      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2016-12-14 07:38:49,264 INFO [NiFi logging handler] org.apache.nifi.StdOut      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2016-12-14 07:38:49,264 INFO [NiFi logging handler] org.apache.nifi.StdOut      at java.lang.Thread.run(Thread.java:745)
```

**Comment by apsaltis** [comment]
@ddewaele That is interesting, I have not seen that but will try and track down what is happening

**Comment by ddewaele** [comment]
I never saw it during testing with my mock tcp server on my local machine, but when I hooked it up to a an actual device it happened a lot. I can reproduce it in my debugger by suspending the thread on my mock tcp server that is writing data on the channel.

**Comment by apsaltis** [comment]
That would be awesome. I have been testing it with https://github.com/machinezone/tcpkali, but need to hook it up to a real device. What is your device you are using?

**Comment by ddewaele** [comment]
I'm using a Moxa nport.

The read method on socketChannel does not support timeouts and can hang indefinitely in blocking mode. Specifying timeouts on the socket won't work.

http://stackoverflow.com/questions/2866557/timeout-for-socketchannel-doesnt-work

**Comment by apsaltis** [comment]
Looks like a fun device.

Can also set the channel to non-blocking mode and properly handle waiting for the connection to be established.
