### ISSUE TITLE
onSchedule timeouts

### ISSUE THREAD

**Issue by ddewaele** [apsaltis/nifi-gettcp-bundle#9]
OnScheduled method should contain code that executes very quick, short-lived tasks
```
2016-12-15 14:13:10,813 ERROR [StandardProcessScheduler Thread-3] org.apache.nifi.processors.gettcp.GetTCP GetTCP[id=05faf95c-0158-1000-1aa8-e92add05c423] Caught exception trying to connect to the host: xx.xx.xx.xx. Depending on configuration may try and reconnect.: java.net.ConnectException: Operation timed out

2016-12-15 14:11:55,397 ERROR [StandardProcessScheduler Thread-2] org.apache.nifi.processors.gettcp.GetTCP 
java.lang.RuntimeException: Timed out while executing one of processor's OnScheduled task.
        at org.apache.nifi.controller.StandardProcessorNode.invokeTaskAsCancelableFuture(StandardProcessorNode.java:1412) ~[na:na]
        at org.apache.nifi.controller.StandardProcessorNode.access$100(StandardProcessorNode.java:96) ~[na:na]
        at org.apache.nifi.controller.StandardProcessorNode$1.run(StandardProcessorNode.java:1240) ~[na:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_40]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_40]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_40]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_40]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_40]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_40]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40]
Caused by: java.util.concurrent.TimeoutException: null
        at java.util.concurrent.FutureTask.get(FutureTask.java:205) [na:1.8.0_40]
        at org.apache.nifi.controller.StandardProcessorNode.invokeTaskAsCancelableFuture(StandardProcessorNode.java:1397) ~[na:na]
        ... 9 common frames omitted
```

**Comment by vyshaliN** [comment]
What was the solution derived to overcome this? I'm also stuck here.

**Comment by ddewaele** [comment]
I think the gettcp processor is now in the main nifi codebase. This repo is probably obsolete.

**Comment by apsaltis** [comment]
Correct and i will close this repo.
